---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - opensearch.vanchonlee.dev
  resources:
  - clusterautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.vanchonlee.dev
  resources:
  - clusterautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.vanchonlee.dev
  resources:
  - clusterautoscalers/status
  verbs:
  - get
  - patch
  - update
